# Generated by Django 3.2.4 on 2021-06-13 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations_event', '0002_auto_20210612_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AlterModelOptions(
            name='spot',
            options={'verbose_name': 'Местоположение мероприятия', 'verbose_name_plural': 'Местоположения мероприятия'},
        ),
        migrations.AlterField(
            model_name='spot',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='ebs_id',
            field=models.IntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='spot',
            name='ebs_title',
            field=models.IntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='spot',
            name='foundation_id',
            field=models.IntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='spot',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='place_type_id',
            field=models.IntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='spot',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(max_length=255, upload_to='photos/%Y/%m/%d/')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations_event.category')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations_event.spot')),
            ],
        ),
    ]
