# Generated by Django 3.2.4 on 2021-06-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations_event', '0003_auto_20210613_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_time_finish',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время окончания'),
        ),
        migrations.AddField(
            model_name='event',
            name='date_time_start',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время начала'),
        ),
    ]
