# Generated by Django 3.2.4 on 2021-06-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations_event', '0004_auto_20210613_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time_finish',
            field=models.DateTimeField(verbose_name='Дата и время окончания'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time_start',
            field=models.DateTimeField(verbose_name='Дата и время начала'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(to='locations_event.Tags'),
        ),
    ]
