# Generated by Django 3.2.4 on 2021-06-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations_event', '0005_auto_20210613_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Тэги'),
        ),
    ]
